### ISSUE TITLE
More Documentation and Sourcing?

### ISSUE THREAD

**Issue by ghost** [suodrazah/murdoch_blocklist#1]
Hey, this is a really powerful project, but I think it'll seem suspicious if it never gets documented?

A readme describing how the information was compiled, sources of information to help keep it up to date, instructions and criteria for volunteers who want to help keep it updated.. etc.

**Comment by suodrazah** [comment]
Sources are difficult, Murdoch is a tricky bastard.

I'll be personally, manually and irregularly updating it. I've added a basic readme, open to suggestions for changes if you have any.

**Comment by ghost** [comment]
:) Sure, thanks for that improvement.
Some idea of where you got the current domain list would be a great start, though. Are you going by public registries of beneficial ownership, or just the list of News Corp Subsidiaries, for example? OpenCorporates? Wikipedia?
It would help others to contribute.

**Comment by suodrazah** [comment]
I've put the original source up. I don't have twitter but you're welcome to notify emilyapocalypse of the repo and maybe we can help one another keep the list updated as we both add to it. No idea if they are a GitHub user.

**Comment by suodrazah** [comment]
This is a good reference for AU https://www.newscorpaustralia.com/brands/

Including the potential sources you mentioned earlier.

I'll go through it at a later date and update the list with anything missing. With coffee.
